version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        image: mongo:latest
        container_name: 'database'
        environment:
            MONGO_INITDB_DATABASE: db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:                                                                
           - ./database/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
           - ./database/storage/:/data/db
        ports:
            - '27017-27019:27017-27019'
    
    backend:
        image: node:latest
        container_name: 'backend'
        command: sh -c 'npm install && npm start'
        environment:
            NODE_ENV: development
            PORT: 3000
        ports:
            - '3000:3000'
        working_dir: /root/backend
        volumes:
            - ./backend:/root/backend:cached
        depends_on:
            - database
    
    frontend:
        image: node:12
        container_name: 'frontend'
        command: sh -c 'npm install && npx ng serve -o'
        environment:
            PORT: 4200
        ports:
            - '4200:4200'
        working_dir: /root/frontend
        volumes:
            - ./frontend:/root/frontend:cached
        depends_on: 
            - database
            - backend

