version: '3.7'

services:                                                                       
    database:                                                   
        image: vlasebian/idp-database:latest
        volumes:
            - ./dbdata:/data/db
        networks:
            - idpnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement: 
                constraints: [node.role == manager]
    
    backend:
        image: vlasebian/idp-backend:latest
        command: npm run dev-start
        ports:
            - '3000:3000'
        networks:
            - idpnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        depends_on:
            - database
    
    frontend:
        image: vlasebian/idp-frontend:latest
        command: /bin/sh -c "exec nginx -g 'daemon off;'"
        ports:
            - '80:80'
        networks:
            - idpnet
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        depends_on: 
            - backend
    
    admin:
        image: vlasebian/idp-admin:latest
        command: /bin/sh -c "exec nginx -g 'daemon off;'"
        ports:
            - '81:80'
        networks:
            - idpnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        depends_on: 
            - backend

    prometheus:
        image: vlasebian/idp-monitor:latest
        ports:
            - '9090:9090'
        networks:
            - idpnet

    node_exporter:
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'
        networks:
            - idpnet

networks:
    idpnet:
