version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        container_name: 'app-database'
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: db
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:                                                                
           - ./database/storage/:/data/db
        expose:
           - 27017
    
    backend:
        container_name: 'app-backend'
        build: ./backend
        command: npm run dev-start
        ports:
            - '3000:3000'
        depends_on:
            - database
    
    frontend:
        container_name: 'app-frontend'
        build: ./frontend
        command: npx ng serve -o --host 0.0.0.0
        ports:
            - '4200:4200'
        depends_on: 
            - backend
    
    admin:
        container_name: 'app-admin'
        build: ./admin
        command: npx ng serve -o --host 0.0.0.0
        ports:
            - '4201:4200'
        depends_on: 
            - backend

    grafana:
        container_name: 'app-grafana'
        image: grafana/grafana:latest
        ports:
            - '3001:3000'
        depends_on: 
            - database
