version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: recommendr
        volumes:                                                                
           - ./database/storage/:/data/db
           - ./database/init/init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro
        expose:
           - 27017
    
    backend:
        image: node:latest
        command: sh -c 'npm install && npm run dev-start'
        ports:
            - '3000:3000'
        working_dir: /root/backend
        volumes:
            - ./backend/src:/root/backend:cached
        depends_on:
            - database
    
    frontend:
        image: node:latest
        command: sh -c 'npm install && npx ng serve -o --proxy-config proxy.config.json --host 0.0.0.0'
        ports:
            - '4200:4200'
        working_dir: /root/frontend/
        volumes:
            - ./frontend/src:/root/frontend:cached
        depends_on: 
            - database
            - backend
    
    admin:
        image: node:latest
        command: sh -c 'npm install && npx ng serve -o --proxy-config proxy.config.json --host 0.0.0.0'
        ports:
            - '4201:4200'
        working_dir: /root/admin
        volumes:
            - ./admin/src:/root/admin:cached
        depends_on:
            - database

