version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        build: ./database
        command: mongod
        networks:
            - idpnet
        expose:
            - 27017
    
    backend:
        build: ./backend
        command: npm run dev-start
        ports:
            - '3000:3000'
        networks:
            - idpnet
        depends_on:
            - database
    
    frontend:
        build: ./frontend
        command: /bin/sh -c "exec nginx -g 'daemon off;'"
        ports:
            - '80:80'
        networks:
            - idpnet
        depends_on: 
            - backend
    
    admin:
        build: ./admin
        command: /bin/sh -c "exec nginx -g 'daemon off;'"
        ports:
            - '81:80'
        networks:
            - idpnet
        depends_on: 
            - backend

    prometheus:
        build: ./prometheus
        ports:
            - '9090:9090'
        networks:
            - idpnet

    node_exporter:
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'
        networks:
            - idpnet

networks:
    idpnet:
