version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: db
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:                                                                
           - ./database/storage/:/data/db
        expose:
           - 27017
    
    backend:
        image: node:latest
        command: sh -c 'npm install && npm run dev-start'
        environment:
            NODE_ENV: development
            PORT: 3000
        ports:
            - '3000:3000'
        working_dir: /root/backend
        volumes:
            - ./backend/src:/root/backend:cached
        depends_on:
            - database
    
    frontend:
        image: node:latest
        command: sh -c 'npm install && npx ng serve --host 0.0.0.0'
        #environment:
        #    PORT: 4200
        ports:
            - '4200:4200'
        working_dir: /root/frontend/
        volumes:
            - ./frontend/src:/root/frontend:cached
        depends_on: 
            - database
            - backend
    
    admin:
        image: node:latest
        command: sh -c 'npm install && npx ng serve --host 0.0.0.0'
        #environment:
        #    NODE_ENV: development
        #    PORT: 4200
        ports:
            - '4201:4200'
        working_dir: /root/admin
        volumes:
            - ./admin/src:/root/admin:cached
        depends_on:
            - database

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3001:3000'

