version: '3.7'
                                                                                
services:                                                                       
    database:                                                                         
        container_name: 'app-database'
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
        volumes:                                                                
           - ./database/init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
           - ./database/storage/:/data/db
        ports:
            - '27017-27019:27017-27019'
    
    backend:
        container_name: 'app-backend'
        build: ./backend
        ports:
            - '3000:3000'
        depends_on:
            - admin
    
    frontend:
        container_name: 'app-frontend'
        build: ./frontend
        ports:
            - '4200:4200'
        depends_on: 
            - backend
    
    admin:
        container_name: 'app-admin'
        build: ./admin
        ports:
            - '3000:3001'
        depends_on: 
            - database

    grafana:
        container_name: 'app-grafana'
        image: grafana/grafana:latest
        ports:
            - '3000:3002'
        depends_on: 
            - database

