global:
    scrape_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets:
              - 'localhost:9090'

    - job_name: 'backend'
      static_configs:
          - targets:
              - 'backend:3000'

    - job_name: 'node_exporter'
      static_configs:
          - targets:
              - 'node_exporter:9100'

